---
- name: copy deploy script
  copy:
    src: files/traefik.sh
    dest: /root/traefik.sh
    mode: 755
- name: run deploy script
  command: sh /root/traefik.sh
  environment:
    HOSTNAME: "{{fqdn}}"
    ANYCAST_IP: "{{anycast_ip}}"
